### ISSUE TITLE
Exception when using require_keycloak_role

### ISSUE THREAD

**Issue by SUL-sj** [vishnu667/flask-oidc2#2]
When using the newly introduced _require_keycloak_role_ check, I am getting the following error:

```
ERROR:waitress:Exception while serving /api
scss    | Traceback (most recent call last):
scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
scss    |     task.service()
scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
scss    |     self.execute()
scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
scss    |     app_iter = self.channel.server.application(environ, start_response)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
scss    |     return self.wsgi_app(environ, start_response)
scss    |   File "/usr/local/lib/python3.7/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
scss    |     return self.app(environ, start_response)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
scss    |     response = self.handle_exception(e)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
scss    |     reraise(exc_type, exc_value, tb)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
scss    |     raise value
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
scss    |     response = self.full_dispatch_request()
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
scss    |     rv = self.handle_user_exception(e)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
scss    |     reraise(exc_type, exc_value, tb)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
scss    |     raise value
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
scss    |     rv = self.dispatch_request()
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
scss    |     return self.view_functions[rule.endpoint](**req.view_args)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 888, in decorated
scss    |     return view_func(*args, **kwargs)
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 514, in decorated
scss    |     pre, tkn, post = self.get_access_token().split('.')
scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 271, in get_access_token
scss    |     self.credentials_store[g.oidc_id_token['sub']])
scss    | TypeError: 'NoneType' object is not subscriptable
```

this is my method-header:

 ```
@app.route('/api/', methods=['GET'], strict_slashes=False)
 @oidc.accept_token(require_token=True)
 @oidc.require_keycloak_role(client=config['KEYCLOAK']['Client'], role=config['KEYCLOAK']['User'])
def home:
```

The keycloak values are correct, I double checked. So as the stacktrace only mentions the flask and oidc methods, I could need some help with this...

**Comment by reno9** [comment]
> When using the newly introduced _require_keycloak_role_ check, I am getting the following error:
> 
> ```
> ERROR:waitress:Exception while serving /api
> scss    | Traceback (most recent call last):
> scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
> scss    |     task.service()
> scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
> scss    |     self.execute()
> scss    |   File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
> scss    |     app_iter = self.channel.server.application(environ, start_response)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
> scss    |     return self.wsgi_app(environ, start_response)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
> scss    |     return self.app(environ, start_response)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
> scss    |     response = self.handle_exception(e)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
> scss    |     reraise(exc_type, exc_value, tb)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
> scss    |     raise value
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
> scss    |     response = self.full_dispatch_request()
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
> scss    |     rv = self.handle_user_exception(e)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
> scss    |     reraise(exc_type, exc_value, tb)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
> scss    |     raise value
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
> scss    |     rv = self.dispatch_request()
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
> scss    |     return self.view_functions[rule.endpoint](**req.view_args)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 888, in decorated
> scss    |     return view_func(*args, **kwargs)
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 514, in decorated
> scss    |     pre, tkn, post = self.get_access_token().split('.')
> scss    |   File "/usr/local/lib/python3.7/dist-packages/flask_oidc/__init__.py", line 271, in get_access_token
> scss    |     self.credentials_store[g.oidc_id_token['sub']])
> scss    | TypeError: 'NoneType' object is not subscriptable
> ```
> 
> this is my method-header:
> 
> ```
> @app.route('/api/', methods=['GET'], strict_slashes=False)
> @oidc.accept_token(require_token=True)
> @oidc.require_keycloak_role(client=config['KEYCLOAK']['Client'], role=config['KEYCLOAK']['User'])
> def home:
> ```
> 
> The keycloak values are correct, I double checked. So as the stacktrace only mentions the flask and oidc methods, I could need some help with this...
Maybe you can try logout and then login again. You can refer to https://github.com/puiterwijk/flask-oidc/issues/5#issuecomment-86187023 for more information.

**Comment by xorwow** [comment]
I am facing the same issue. To hopefully add some context to this, the bug can be traced back to the method `get_access_token()` not always returning a token: When a user freshly logs in, the method (mostly) returns the actual token. But other times it will fail (return `None`) seemingly at random. Since the `require_keycloak_role` decorator uses `get_access_token` internally, when the token fetch fails, the decorator also fails. This does not affect the `require_login` decorator, which always seems to work. Is there any update on this / the project still under development?

**Comment by xorwow** [comment]
Addendum: A persistent cred store seems to fix this issue, but must be built yourself. The included store is non-persistent.
Quick tutorial for how a CredStore should look:

```
# Create a persistent store, which takes the sub (a kind of token ID) and the token to store/retrieve
class MyStore(dict):
    def __setitem__(self, sub, item):
        # Write the key-value pair somewhere persistent, like a json file (mind multithreaded access)
        pass

    def __getitem__(self, sub):
        # Read the key-value pair from your persistent medium (mind multithreaded access)
        # Raise a KeyError if the sub has not been stores yet! This will result in get_access_token() returning None.
        pass

# Where you normally create the OIDC object, include your persistent store:
oidc = OpenIDConnect(app, credentials_store=MyStore())
```
